#! /bin/bash

declare -A BG
BG["day"]="https://cdna.artstation.com/p/assets/images/images/058/334/668/4k/arseniy-chebynkin-gg1.jpg"
BG["sunset"]="https://cdnb.artstation.com/p/assets/images/images/058/334/671/4k/arseniy-chebynkin-gg2.jpg"
BG["evening"]="https://cdna.artstation.com/p/assets/images/images/058/334/674/4k/arseniy-chebynkin-gg3.jpg"
BG["night"]="https://cdnb.artstation.com/p/assets/images/images/058/334/681/4k/arseniy-chebynkin-gg4.jpg"
export BG
